# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Instagram Like App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Instagram Like App
    pod "Parse"
    pod "AlamofireImage"
    pod "MessageInputBar"

  target 'Instagram Like AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Instagram Like AppUITests' do
    # Pods for testing
  end

end
